// Topic lists ported verbatim from the old cron_daily.php / cron_daily2.php /
// cron_daily3.php scripts.

const TOP_PERFORMERS = [
  'Aulin', 'Nimesulide', 'Paracetamolo', 'Tachipirina 1000', 'Tachipirina 500',
  'Oki', 'Brufen', 'Bentelan', 'Cortisone', 'Antibiotico', 'Augmentin',
];

const STANDARD_DRUG_TOPICS = [
  'Oki Bustine', 'Oki Gocce', 'Brufen 600', 'Brufen 400', 'Bentelan 1mg',
  'Spidifen', 'Voltaren', 'Voltaren Emulgel', 'Muscoril', 'Toradol', 'Synflex', 'Moment', 'Moment Act',
  'Nurofen', 'Nurofen Influenza e Raffreddore', 'Enantyum', 'Flector', 'Artrosilene', 'Fastum Gel', 'Lasonil',
  'Buscopan', 'Antispasmina', 'Doliact', 'Co-Efferalgan', 'Efferalgan', 'Aspirina', 'Aspirina C', 'Vivin C',
  'Zerinol', 'Actigrip', 'Tachifludec', 'Neo Borocillina', 'Benagol', 'Borocillina', 'Froben Gola', 'Iodosan',
  'Tantum Verde', 'Ketodol', 'Saridon', 'Novalgina', 'Algix', 'Arcoxia', 'Celebrex', 'Dicloreum', 'Indoxen',
  'Feldene', 'Brezin', 'Orudis', 'Ketoprofene', 'Ibuprofene', 'Naproxene', 'Deltacortene',
  'Zitromax', 'Amoxicillina', 'Klacid', 'Ciproxin', 'Normix', 'Zimox', 'Velamox', 'Clavulin',
  'Macladin', 'Veclam', 'Levoxacin', 'Tavanic', 'Bassado', 'Miraclin', 'Rifacol', 'Bimixin', 'Monuril',
  'Cistalgan', 'Fosfomicina', 'Cefixoral', 'Supracef', 'Rocefin', 'Glazidim', 'Panacef', 'Gentamicina',
  'Gentalyn', 'Gentalyn Beta', 'Streptosil', 'Aureomicina', 'Bactroban', 'Fucidin', 'Tobral', 'Exocin',
  'Gaviscon', 'Maalox', 'Riopan', 'Biochetasi', 'Imodium', 'Enterogermina', 'Codex', 'Yovis', 'Fermenti Lattici',
  'Plasil', 'Peridon', 'Lansox', 'Pantorc', 'Lucen', 'Omeprazen', 'Nexium', 'Esopral', 'Peptazol', 'Antra',
  'Mepral', 'Limpidex', 'Levopraid', 'Geffer', 'Citrosodina', 'Brioschi', 'Mylicon', 'Simecrin', 'Valpinax',
  'Debridat', 'Duspatal', 'Obispax', 'Spasmomen', 'Buscopan Compositum', 'Dissenten', 'Loperamide',
  'Cardioaspirina', 'Coumadin', 'Lasix', 'Triatec', 'Ramipril', 'Norvasc', 'Sequacor', 'Lobivon', 'Totalip',
  'Torvast', 'Crestor', 'Simvastatina', 'Atorvastatina', 'Eutirox', 'Tapazole', 'Metforal', 'Glucophage',
  'Xanax', 'Lexotan', 'Valium', 'En', 'Tavor', 'Minias', 'Halcion', 'Seropram', 'Cipralex', 'Zoloft',
  'Fluimucil', 'Bisolvon', 'Levotuss', 'Seki', 'Bronchenolo', 'Lisomucil', 'Mucosolvan', 'Sobrepin',
  'Aircort', 'Clenil', 'Pulmaxan', 'Foster', 'Symbicort', 'Seretide', 'Aliflus', 'Fluspiral', 'Ventolin',
  'Broncovaleas', 'Spiriva', 'Ultibro', 'Onbrez', 'Singulair', 'Montek', 'Rinazina', 'Vicks Sinex',
  'Multicentrum', 'Supradyn', 'Polase', 'Magnesio Supremo', 'Carnidyn', 'Sustenium', 'Be-Total', 'Benexol',
  'Viagra', 'Cialis', 'Levitra',
];

export const DRUG_TOPICS = [...TOP_PERFORMERS, ...STANDARD_DRUG_TOPICS];

const WELLNESS_TOPICS_BASE = [
  'I benefici incredibili dello Zenzero per la digestione', 'Perché dovresti mangiare 3 noci al giorno',
  'Acqua e limone al mattino: mito o realtà?', 'I segreti della Dieta Mediterranea per la longevità',
  'Come il Magnesio aiuta a dormire meglio', 'Carenza di Vitamina D: i segnali da non ignorare',
  'Perché i mirtilli sono considerati un superfood', 'La verità sullo zucchero bianco e i suoi effetti',
  "Olio extravergine d'oliva: l'oro liquido per il cuore", 'Le proprietà nascoste della Curcuma',
  'Probiotici naturali: quali cibi li contengono', 'Come disintossicare il fegato naturalmente',
  "I benefici del tè verde contro l'invecchiamento", 'Perché le banane fanno bene agli sportivi',
  'Omega-3: perché sono essenziali per il cervello', 'Il potere antiossidante del cioccolato fondente',
  'Come ridurre il colesterolo a tavola', "I benefici dell'avocado per la pelle",
  'Perché mangiare lentamente aiuta a dimagrire', 'Le migliori tisane per sgonfiare la pancia',
  'Semi di chia: piccoli ma potenti', 'I benefici del digiuno intermittente spiegati bene',
  "Come combattere la ritenzione idrica con l'alimentazione", 'Perché le fibre sono fondamentali per l\'intestino',
  'I cibi che aumentano la concentrazione', 'Miele vs Zucchero: quale scegliere?',
  'I benefici del succo di melograno', 'Come preparare una colazione sana ed energetica',
  'Gli effetti della caffeina sul nostro corpo', 'Perché mangiare verdure di stagione è meglio',
  'Perché sbadigliamo? La scienza dietro lo sbadiglio', 'Come funziona davvero il sistema immunitario',
  'Perché abbiamo il singhiozzo e come farlo passare', "Il mistero dell'appendice: serve davvero a qualcosa?",
  'Perché la pelle diventa d\'oca quando abbiamo freddo', 'Cosa succede al corpo quando smettiamo di fumare',
  "Perché i capelli diventano bianchi con l'età", 'Il ruolo della melatonina nel ciclo del sonno',
  'Perché abbiamo le impronte digitali uniche', 'Come il cervello memorizza i ricordi',
  'Perché starnutiamo? La funzione protettiva dello starnuto', 'Cosa sono i crampi muscolari e perché vengono',
  'Perché il cuore batte più forte quando abbiamo paura', 'Come funzionano i vaccini nel nostro corpo',
  'Perché ci viene la febbre? Il meccanismo di difesa', 'La differenza tra virus e batteri spiegata semplice',
  'Perché il sangue è rosso?', 'Come guariscono le ferite: il processo incredibile',
  'Perché abbiamo due reni se possiamo vivere con uno', 'Cosa succede durante la digestione',
  'Il microbioma intestinale: il nostro secondo cervello', 'Perché ci fischiano le orecchie (acufene)',
  'Come funziona la vista e perché peggiora', 'Perché sudiamo? La termoregolazione corporea',
  'Cosa provoca il mal di testa da tensione',
  '10 consigli per smettere di russare', 'Come proteggere la vista lavorando al computer',
  'I benefici della camminata veloce quotidiana', "Come migliorare la postura in ufficio",
  "Tecniche di respirazione per calmare l'ansia", "L'importanza di bere 2 litri d'acqua al giorno",
  'Come prevenire il mal di schiena lombare', 'I benefici della doccia fredda al mattino',
  "Come prendersi cura della pelle in inverno", "Perché è importante usare la protezione solare sempre",
  'Consigli per mantenere il cervello giovane', 'Come evitare le gambe gonfie in estate',
  'I benefici dello stretching prima di dormire', 'Come gestire lo stress da lavoro',
  "L'importanza dell'igiene del sonno", 'Come prevenire le carie dentali naturalmente',
  'I rischi della vita sedentaria e come muoversi di più', 'Come rinforzare le unghie fragili',
  'Rimedi naturali per la pelle secca', 'Come combattere la stanchezza cronica',
  'I benefici di leggere un libro prima di dormire', 'Come migliorare la circolazione sanguigna',
  'Perché ridere fa bene alla salute', 'Come prevenire il raffreddore stagionale',
  'I benefici del contatto con la natura',
  'Aceto di mele: usi e benefici per la salute', 'Bicarbonato di sodio: mille usi per il benessere',
  "Come usare l'aloe vera per le scottature", 'Rimedi naturali per il mal di gola',
  'Suffumigi con eucalipto per liberare il naso', 'Camomilla: non solo per dormire',
  "Come usare l'olio di cocco per i capelli", 'Impacchi di ghiaccio o calore? Quando usarli',
  'Zenzero e limone per la nausea', 'Come curare le afte in bocca naturalmente',
  "I benefici dell'argilla verde", 'Olio di tea tree: il disinfettante naturale',
  'Come alleviare il prurito delle punture di zanzara', 'Rimedi per le occhiaie e borse sotto gli occhi',
  'Lavaggi nasali: perché sono importanti',
  'Come riconoscere i sintomi del burnout', "L'importanza di dire no per la salute mentale",
  "Come superare l'ansia da prestazione", 'I benefici della meditazione mindfulness',
  'Perché procrastiniamo e come smettere', 'L\'effetto dei colori sul nostro umore',
  'Come coltivare la gratitudine quotidiana', 'Relazioni tossiche: come riconoscerle',
  "L'importanza del contatto fisico e degli abbracci", 'Come affrontare la solitudine positivamente',
  '5 Miti da sfatare sull\'alimentazione', 'Perché il sale iodato è importante',
  'Differenza tra intolleranza e allergia', 'Cosa mangiare prima di andare in palestra',
  'I benefici del nuoto per la schiena', 'Perché le donne vivono più a lungo degli uomini',
  'Come leggere le etichette alimentari', 'I pericoli delle diete fai-da-te',
  "Perché l'antibiotico non serve per l'influenza", 'Come conservare i cibi in frigo correttamente',
  'I benefici della sauna e del bagno turco', 'Perché ci viene il mal d\'auto',
  'Come scegliere il cuscino giusto per dormire', 'I benefici della vitamina E per la pelle',
  'Perché il calcio è fondamentale per le ossa', 'Come ridurre il consumo di plastica per la salute',
  'I benefici di avere un animale domestico', 'Come preparare uno scrub naturale per il corpo',
  'Perché è importante fare colazione', "Gli effetti dell'alcol sul fegato",
  'Come riconoscere un neo pericoloso', 'I benefici del massaggio terapeutico',
  'Perché abbiamo i denti del giudizio', "Come funziona l'effetto placebo",
  'I rischi dei tatuaggi non sicuri', 'Come proteggere i capelli dal sole',
  'I benefici del pilates per la postura', "Perché l'attività fisica riduce la depressione",
  'Come misurare la pressione correttamente a casa', "I sintomi dell'infarto che tutti dovrebbero conoscere",
  'Cosa fare in caso di piccola ustione domestica', "Perché è importante lavarsi le mani spesso",
  'I benefici del potassio per i muscoli', 'Come integrare il ferro nella dieta vegetariana',
  'Perché il fumo passivo è pericoloso', 'Come scegliere le scarpe giuste per correre',
  'I benefici del ballo per il cervello', 'Perché i bambini hanno bisogno di giocare all\'aperto',
  "Come ridurre l'inquinamento domestico", 'I benefici del silenzio per la mente',
];

const WELLNESS_PREFIXES = ['La verità su', 'Tutto quello che devi sapere su', 'Guida completa a', 'I rischi di', 'I benefici nascosti di'];
const WELLNESS_SUBJECTS = ['Vitamina B12', 'Collagene', 'Acido Ialuronico', 'Zinco', 'Selenio', 'Melograno', 'Papaya', 'Kefir', 'Miso', 'Tofu', 'Seitan', 'Quinoa', 'Amaranto', 'Grano Saraceno', 'Riso Integrale', 'Farro', 'Orzo', 'Avena', 'Segale', 'Miglio'];

export const WELLNESS_TOPICS = [
  ...WELLNESS_TOPICS_BASE,
  ...WELLNESS_PREFIXES.flatMap((p) => WELLNESS_SUBJECTS.map((s) => `${p} ${s}`)),
];

const PROBLEMS_TOPICS_BASE = [
  'Quanto costa un impianto dentale completo?', 'Sbiancamento denti professionale: prezzi e rischi',
  'Faccette dentali: ne vale la pena?', 'Devitalizzazione dente: fa male? Cosa sapere',
  "Apparecchio invisibile: funziona davvero?", 'Protesi mobile o fissa: quale scegliere per gli anziani',
  'Dente del giudizio: quando toglierlo obbligatoriamente', 'Mal di denti improvviso: rimedi immediati notte',
  'Infezione gengivale: sintomi da non ignorare', 'Costo corona dentale in ceramica vs zirconio',
  'Alito cattivo cronico: cause nascoste e cure', 'Bruxismo notturno: il bite serve davvero?',
  'Recessione gengivale: si può curare?', 'Trapianto capelli Turchia vs Italia: la verità',
  'Caduta capelli uomo: Finasteride e Minoxidil rischi', 'Acido Ialuronico filler labbra: quanto dura?',
  'Botox fronte: effetti collaterali e costi', 'Rinoplastica non chirurgica: come funziona',
  'Liposuzione addome: costi e recupero', 'Blefaroplastica: togliere le borse sotto gli occhi',
  'Mastoplastica additiva: tutto quello che devi sapere', 'Rimozione tatuaggi laser: fa male?',
  'Macchie solari viso: trattamenti laser efficaci', 'Mal di schiena lombare: esercizi da evitare',
  'Cervicale infiammata: sintomi vertigini e nausea', 'Sciatalgia: quanto dura e come dormire',
  'Tunnel carpale: quando operare?', 'Artrosi ginocchio: le infiltrazioni funzionano?',
  'Ernia del disco: si riassorbe da sola?', 'Fascite plantare: scarpe consigliate',
  'Dolore alla spalla notturno: cuffia dei rotatori', 'Menisco rotto: si può camminare?',
  'Alluce valgo: tutori funzionano o serve operazione?', 'Osteoporosi cure nuove',
  "Fibromialgia: come ottenere invalidità", 'Cistite post rapporto: come prevenirla',
  'Candida recidivante: dieta e cure', 'Prostatite cronica: si guarisce?',
  'Viagra naturale in erboristeria esiste?', 'Testosterone basso uomo: sintomi e cure',
  'Dolori mestruali forti: quando preoccuparsi', 'Endometriosi: sintomi iniziali',
  'Cisti ovariche: quando operare', 'Migliori creme per dermatite atopica',
  'Come eliminare le macchie solari dal viso', 'Acne tardiva a 30 o 40 anni: cause e cure',
  'Psoriasi: le nuove cure biologiche funzionano?', 'Come togliere le verruche velocemente',
  'Rosacea viso: cosa non mangiare', 'Smagliature rosse vs bianche: quali si tolgono?',
  'Cellulite rimedi efficaci: massaggi o creme?', 'Alopecia areata: lo stress c\'entra?',
  'Migliore crema antirughe dopo i 50 anni', 'Funghi della pelle: come riconoscerli',
  'Mappatura nei: ogni quanto farla', 'Reflusso gastroesofageo: cibi vietati lista completa',
  'Colon irritabile: dieta FODMAP funziona?', 'Helicobacter Pylori: terapia antibiotica pesante',
  'Gastrite nervosa: sintomi e rimedi naturali', 'Emorroidi esterne: quanto durano?',
  'Ragadi anali: creme migliori', 'Gonfiore addominale dopo i pasti: cause',
  'Intolleranza al lattosio: sintomi non intestinali', 'Celiachia sintomi adulti',
  'Diverticolite: cosa mangiare e cosa no', 'Intervento laser occhi: rischi e benefici',
  'Cataratta: quando operare e tempi attesa', 'Glaucoma: si diventa ciechi?',
  'Acufene rimedi: come conviverci', "Apparecchio acustico invisibile: prezzi",
  'Maculopatia: nuove cure', 'Congiuntivite virale o batterica: differenze',
  'Attacchi di panico notturni: cosa fare subito', 'Depressione post partum: quanto dura',
  'Burnout lavorativo: sintomi fisici', 'Ansia generalizzata: farmaci o psicoterapia?',
  'Insonnia cronica: tecniche cognitive comportamentali', 'Melatonina per dormire: crea dipendenza?',
  'Derealizzazione e ansia: come uscirne',
];

const PROBLEMS_PREFIXES = ['Quanto costa curare', 'Rimedi definitivi per', 'Tutto su', 'Rischi e benefici di', 'Migliori trattamenti per'];
const PROBLEMS_CONDITIONS = ["l'Ipertensione", 'il Colesterolo alto', "l'Asma allergica", 'la Bronchite cronica', "l'Otite media", 'la Sinusite', 'la Gotta', 'il Diabete tipo 2'];

export const PROBLEMS_TOPICS = [
  ...PROBLEMS_TOPICS_BASE,
  ...PROBLEMS_PREFIXES.flatMap((p) => PROBLEMS_CONDITIONS.map((c) => `${p} ${c}`)),
];
